# Why Numpy
    Numpy makes more complex calculations easier than lists.

In [7]:
import numpy as np


In [4]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
print(a)
print(b)


[1, 2, 3, 4]
[5, 6, 7, 8]


In [5]:
ab = []
for i in range(len(a)):
    ab.append(a[i]*b[i])
print(ab)


[5, 12, 21, 32]


In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a*b


array([ 5, 12, 21, 32])

# Creating Numpy Array

In [9]:
array = np.array([1, 2, 3, 4, 6])
type(array)

numpy.ndarray

In [10]:
array2 = np.array([13.5, 1, 2, 3, 4])
array2

array([13.5,  1. ,  2. ,  3. ,  4. ])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# ortalması 0, standart sapması 1 olan 3x3 lük bir matris oluşturmak için:
np.random.normal(0, 1, (3,3))

array([[ 0.02608657,  0.17871087, -0.84752956],
       [-1.26181428,  0.53026236,  0.33659381],
       [-1.03837985,  0.55650904,  1.14860322]])

In [19]:
# 0 ile 10 arasında 3x3 lük bir matris oluşturmak için:
np.random.randint(0, 10, (3,3))

array([[1, 2, 0],
       [6, 0, 2],
       [2, 9, 7]])

## Properties 
- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: array veri tipi