# Why Numpy
    Numpy makes more complex calculations easier than lists.

In [1]:
import numpy as np


In [2]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
print(a)
print(b)


[1, 2, 3, 4]
[5, 6, 7, 8]


In [3]:
ab = []
for i in range(len(a)):
    ab.append(a[i]*b[i])
print(ab)


[5, 12, 21, 32]


In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a*b


array([ 5, 12, 21, 32])

# Creating Numpy Array

In [5]:
array = np.array([1, 2, 3, 4, 6])
type(array)

numpy.ndarray

In [6]:
array2 = np.array([13.5, 1, 2, 3, 4])
array2

array([13.5,  1. ,  2. ,  3. ,  4. ])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0, 20, 2) # start, end (exclusive), step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# ortalması 0, standart sapması 1 olan 3x3 lük bir matris oluşturmak için:
np.random.normal(0, 1, (3,3))

array([[-1.57374838,  0.86983481, -2.05698171],
       [ 0.59247865, -0.75222286, -0.20520089],
       [ 0.92038248, -0.76601943,  0.3087073 ]])

In [13]:
# 0 ile 10 arasında 3x3 lük bir matris oluşturmak için:
np.random.randint(0, 10, (3,3))

array([[5, 9, 2],
       [6, 3, 6],
       [2, 8, 1]])

In [14]:
# 3x3 lük birim matris oluşturmak için:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Properties 
- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: array veri tipi

In [15]:
array3 = np.random.randint(0, 10, size=(3, 3))
array3

array([[5, 3, 1],
       [0, 4, 0],
       [1, 1, 6]])

In [16]:
print(array3.ndim)
print(array3.shape)
print(array3.size)
print(array3.dtype)

2
(3, 3)
9
int32


# Reshape

In [17]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Concatenation 

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [21]:
z = np.array([7,8,9])

In [22]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# making 2 dimensional array
a = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([a, a], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting

In [25]:
# n  indexe karşılık n + 1 boyutlu array oluşturur
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
a,b,c = np.split(x, [3, 5])


In [26]:
# iki boyutlu arraylerde split işlemi
m = np.arange(16).reshape((4, 4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
a,b = np.vsplit(m, [2])
print(a, "\n")
print(b)

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
c,d = np.hsplit(m, [2])
print(c, "\n")
print(d)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Sorting

In [29]:
v  = np.random.randint(10, size=(3, 5))
v

array([[9, 8, 2, 9, 5],
       [6, 8, 7, 7, 1],
       [2, 8, 1, 4, 3]])

In [30]:
np.sort(v, axis=0)

array([[2, 8, 1, 4, 1],
       [6, 8, 2, 7, 3],
       [9, 8, 7, 9, 5]])

In [31]:
np.sort(v, axis=1)

array([[2, 5, 8, 9, 9],
       [1, 6, 7, 7, 8],
       [1, 2, 3, 4, 8]])

# İndex ile elaman erişme

In [32]:
a  = np.random.randint(10, size=(3, 5))
a

array([[7, 3, 4, 2, 5],
       [6, 2, 7, 8, 3],
       [5, 5, 7, 7, 2]])

In [33]:
a[1:3, 1:4]


array([[2, 7, 8],
       [5, 7, 7]])

In [34]:
a[1, 1]


2

In [35]:
a[:, 0:1]

array([[7],
       [6],
       [5]])

In [36]:
# alt Küme Üzerinde İşlem Yapmak
b = np.random.randint(16, size=(4, 4))
b

array([[12, 12,  4, 11],
       [ 6, 10,  3, 11],
       [ 1,  8,  5, 12],
       [ 6,  6,  3,  1]])

In [37]:
sub_b = b[:2, :2]
sub_b

array([[12, 12],
       [ 6, 10]])

In [38]:
sub_b[0, 0] = 99
sub_b[1,1] = 999
sub_b

array([[ 99,  12],
       [  6, 999]])

In [39]:
b

array([[ 99,  12,   4,  11],
       [  6, 999,   3,  11],
       [  1,   8,   5,  12],
       [  6,   6,   3,   1]])

In [40]:
m = np.random.randint(20, size=(4, 5))
m

array([[ 2, 12,  0, 12, 17],
       [15,  3,  2,  2,  3],
       [ 3, 18,  7,  4,  4],
       [12, 11,  9,  1, 10]])

In [41]:
# oluşan array üzerinde değişiklik yapmamak için copy() kullanılmalıdır.
sub_m = m[1:3, 2:4].copy()
sub_m

array([[2, 2],
       [7, 4]])

In [42]:
sub_m[0, 0] = 99
sub_m[1, 1] = 999
sub_m

array([[ 99,   2],
       [  7, 999]])

In [43]:
m

array([[ 2, 12,  0, 12, 17],
       [15,  3,  2,  2,  3],
       [ 3, 18,  7,  4,  4],
       [12, 11,  9,  1, 10]])

# Fancy index

In [44]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[1]

2

In [46]:
arr[3]

4

In [47]:
[arr[5], arr[1], arr[3]]

[6, 2, 4]

In [48]:
algetir = [1, 3, 5]


In [49]:
arr[algetir]

array([2, 4, 6])

## İki boyutta fancy

In [50]:
arr1 = np.arange(1, 10).reshape((3, 3))
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
satir = np.array([0, 1])
sutun = np.array([1, 2])    
arr1[satir, sutun]

array([2, 6])

# Koşullu eleman işlemleri

In [52]:
v = np.arange(10, 20, 2)
v

array([10, 12, 14, 16, 18])

In [55]:
v > 13

array([False, False,  True,  True,  True])

In [53]:
v[v > 13]

array([14, 16, 18])

# Math Operations 


In [56]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [57]:
v-1 

array([0, 1, 2, 3, 4])

In [58]:
v * 5

array([ 5, 10, 15, 20, 25])

In [59]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [60]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [61]:
np.multiply(v, 5)

array([ 5, 10, 15, 20, 25])

In [62]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [63]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [64]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [65]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [66]:
v % 2 

array([1, 0, 1, 0, 1], dtype=int32)

In [67]:
np.mod(v, 2)    

array([1, 0, 1, 0, 1], dtype=int32)

In [68]:
np.absolute(np.array([-3]))

array([3])

In [69]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [70]:
?np

Type:        module
String form: <module 'numpy' from 'd:\\Anaconda\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\anaconda\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 

In [ ]:
# Cheat Sheet
# https://assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

# iki bilinmeyenli denklem çözümü


5 * X0 + X1 =12

X0 + 3 *X1 = 10 

In [76]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
a

array([[5, 1],
       [1, 3]])

In [78]:
b

array([12, 10])

In [81]:
x = np.linalg.solve(a, b)
x
# x0 = 1.8571428  //  x1 = 2.71428571

array([1.85714286, 2.71428571])