In [2]:
import pandas as pd 
import numpy as np

In [5]:
pd.Series([10,22,33,54,56])

0    10
1    22
2    33
3    54
4    56
dtype: int64

In [6]:
series = pd.Series([10,22,33,54,56])
type(series)

pandas.core.series.Series

In [7]:
series.axes 

[RangeIndex(start=0, stop=5, step=1)]

In [8]:
series.dtype

dtype('int64')

In [9]:
series.size

5

In [10]:
series.ndim

1

In [16]:
series.values

array([10, 22, 33, 54, 56], dtype=int64)

In [17]:
series.head(3)

0    10
1    22
2    33
dtype: int64

In [18]:
series.tail(3)

2    33
3    54
4    56
dtype: int64

# Indexing 

In [19]:
pd.Series([10,22,33,54,56], index = [1,3,5,7,9])

1    10
3    22
5    33
7    54
9    56
dtype: int64

In [20]:
pd.Series([10,22,33,54,56], index = ["a", "b", "c", "d", "e"])

a    10
b    22
c    33
d    54
e    56
dtype: int64

In [21]:
series = pd.Series([10,22,33,54,56], index = ["a", "b", "c", "d", "e"])

In [22]:
series["a"]

10

In [23]:
series["a": "c"]

a    10
b    22
c    33
dtype: int64

# creating pandas series from dictinories

In [24]:
dictionary = {"reg": 10, "log": 11, "cart": 12}
dictionary

{'reg': 10, 'log': 11, 'cart': 12}

In [25]:
dictSeries = pd.Series(dictionary)

In [26]:
dictSeries

reg     10
log     11
cart    12
dtype: int64

In [29]:
pd.concat([series, dictSeries], axis = 0)

a       10
b       22
c       33
d       54
e       56
reg     10
log     11
cart    12
dtype: int64

## Eleman İşlemleri

In [33]:
a = np.array([1,2,333,44,562, 14, 53])
series = pd.Series(a)
series

0      1
1      2
2    333
3     44
4    562
5     14
6     53
dtype: int32

In [34]:
series[0]

1

In [35]:
series[3]

44

In [36]:
series[0:3]

0      1
1      2
2    333
dtype: int32

In [37]:
series = pd.Series([12, 334, 2, 4, 51, 5, 1, 543, 14,], index=[
                   "a", "b", "c", "d", "e", "f", "g", "h", "i"])
series

a     12
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64

In [38]:
series.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [39]:
series.keys

<bound method Series.keys of a     12
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64>

In [41]:
list(series.items())

[('a', 12),
 ('b', 334),
 ('c', 2),
 ('d', 4),
 ('e', 51),
 ('f', 5),
 ('g', 1),
 ('h', 543),
 ('i', 14)]

In [42]:
"a" in series

True

In [44]:
#fancy eleman 
series[["a", "b"]]  

a     12
b    334
dtype: int64

In [45]:
series["a"] = 999

In [46]:
series

a    999
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64

In [47]:
series["a": "c"]

a    999
b    334
c      2
dtype: int64

# Panda DataFrame

In [48]:
l = [1,2,3,4,5,6,7,8,9]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
df = pd.DataFrame(l, columns = ["degisken_ismi"])
df

degisken_ismi
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9

In [52]:
m = np.arange(1,10).reshape((3,3))
m 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])

In [59]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [60]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [61]:
df.columns = ["deg1", "deg2", "deg3"]

In [62]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [63]:
type(df)

pandas.core.frame.DataFrame

In [64]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [65]:
df.shape

(3, 3)

In [66]:
df.size

9

In [68]:
df.ndim

2

In [69]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
type(df.values)

numpy.ndarray

In [71]:
df.head(2)

deg1  deg2  deg3
0     1     2     3
1     4     5     6

In [72]:
df.tail(2)

deg1  deg2  deg3
1     4     5     6
2     7     8     9