In [2]:
import pandas as pd 
import numpy as np

In [3]:
pd.Series([10,22,33,54,56])

0    10
1    22
2    33
3    54
4    56
dtype: int64

In [4]:
series = pd.Series([10,22,33,54,56])
type(series)

pandas.core.series.Series

In [5]:
series.axes 

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
series.dtype

dtype('int64')

In [7]:
series.size

5

In [8]:
series.ndim

1

In [9]:
series.values

array([10, 22, 33, 54, 56], dtype=int64)

In [10]:
series.head(3)

0    10
1    22
2    33
dtype: int64

In [11]:
series.tail(3)

2    33
3    54
4    56
dtype: int64

# Indexing 

In [12]:
pd.Series([10,22,33,54,56], index = [1,3,5,7,9])

1    10
3    22
5    33
7    54
9    56
dtype: int64

In [13]:
pd.Series([10,22,33,54,56], index = ["a", "b", "c", "d", "e"])

a    10
b    22
c    33
d    54
e    56
dtype: int64

In [14]:
series = pd.Series([10,22,33,54,56], index = ["a", "b", "c", "d", "e"])

In [15]:
series["a"]

10

In [16]:
series["a": "c"]

a    10
b    22
c    33
dtype: int64

# creating pandas series from dictinories

In [17]:
dictionary = {"reg": 10, "log": 11, "cart": 12}
dictionary

{'reg': 10, 'log': 11, 'cart': 12}

In [18]:
dictSeries = pd.Series(dictionary)

In [19]:
dictSeries

reg     10
log     11
cart    12
dtype: int64

In [20]:
pd.concat([series, dictSeries], axis = 0)

a       10
b       22
c       33
d       54
e       56
reg     10
log     11
cart    12
dtype: int64

## Eleman İşlemleri

In [21]:
a = np.array([1,2,333,44,562, 14, 53])
series = pd.Series(a)
series

0      1
1      2
2    333
3     44
4    562
5     14
6     53
dtype: int32

In [22]:
series[0]

1

In [23]:
series[3]

44

In [24]:
series[0:3]

0      1
1      2
2    333
dtype: int32

In [25]:
series = pd.Series([12, 334, 2, 4, 51, 5, 1, 543, 14,], index=[
                   "a", "b", "c", "d", "e", "f", "g", "h", "i"])
series

a     12
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64

In [26]:
series.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [27]:
series.keys

<bound method Series.keys of a     12
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64>

In [28]:
list(series.items())

[('a', 12),
 ('b', 334),
 ('c', 2),
 ('d', 4),
 ('e', 51),
 ('f', 5),
 ('g', 1),
 ('h', 543),
 ('i', 14)]

In [29]:
"a" in series

True

In [30]:
#fancy eleman 
series[["a", "b"]]  

a     12
b    334
dtype: int64

In [31]:
series["a"] = 999

In [32]:
series

a    999
b    334
c      2
d      4
e     51
f      5
g      1
h    543
i     14
dtype: int64

In [33]:
series["a": "c"]

a    999
b    334
c      2
dtype: int64

# Panda DataFrame

In [34]:
l = [1,2,3,4,5,6,7,8,9]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
df = pd.DataFrame(l, columns = ["degisken_ismi"])
df

degisken_ismi
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9

In [36]:
m = np.arange(1,10).reshape((3,3))
m 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])

In [38]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [39]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [40]:
df.columns = ["deg1", "deg2", "deg3"]

In [41]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [42]:
type(df)

pandas.core.frame.DataFrame

In [43]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [44]:
df.shape

(3, 3)

In [45]:
df.size

9

In [46]:
df.ndim

2

In [47]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
type(df.values)

numpy.ndarray

In [49]:
df.head(2)

deg1  deg2  deg3
0     1     2     3
1     4     5     6

In [50]:
df.tail(2)

deg1  deg2  deg3
1     4     5     6
2     7     8     9

In [51]:
s = np.random.randint(1, 30, size=(5, 3))
s


array([[ 8,  5, 16],
       [22,  2, 14],
       [21, 29, 27],
       [ 3,  1, 14],
       [ 1,  4,  6]])

In [52]:
df = pd.DataFrame(s, columns=["var1", "var2", "var3"])
df

var1  var2  var3
0     8     5    16
1    22     2    14
2    21    29    27
3     3     1    14
4     1     4     6

In [53]:
df[0:1]

var1  var2  var3
0     8     5    16

In [54]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [55]:
df.index = ["a", "b", "c", "d", "e"]

In [56]:
df

var1  var2  var3
a     8     5    16
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

# silme işlemi

In [57]:
df.drop("a", axis = 0)

var1  var2  var3
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

In [58]:
df

var1  var2  var3
a     8     5    16
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

In [59]:
df.drop("a", axis = 0, inplace = True)

In [60]:
df

var1  var2  var3
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

In [61]:
# creating var3 from var1 * var2

df["var4"] = df["var1"] * df["var2"]

In [62]:
df

var1  var2  var3  var4
b    22     2    14    44
c    21    29    27   609
d     3     1    14     3
e     1     4     6     4

In [63]:
df.drop("var4", axis = 1)

var1  var2  var3
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

In [64]:
df

var1  var2  var3  var4
b    22     2    14    44
c    21    29    27   609
d     3     1    14     3
e     1     4     6     4

In [65]:
df.drop("var4", axis=1, inplace=True)

In [66]:
df

var1  var2  var3
b    22     2    14
c    21    29    27
d     3     1    14
e     1     4     6

# gözlem ve değişken seçimi: loc & iloc

In [68]:
m = np.random.randint(1, 30, size=(10, 3))
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df

var1  var2  var3
0     9     2    18
1     2    13    23
2    15     1    26
3    24     2    25
4    23     3     2
5    12    10     4
6    10     6     7
7    28     5    28
8     9    14    10
9    23     2    26

In [73]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.
df.loc[0:3]

var1  var2  var3
0     9     2    18
1     2    13    23
2    15     1    26
3    24     2    25

In [74]:
#iloc: alışık olduğumuz indexleme mantığıyla seçim yapmak için kullanılır.
df.iloc[0:3]

var1  var2  var3
0     9     2    18
1     2    13    23
2    15     1    26

In [77]:
df.iloc[2:, 0:2]

var1  var2
2    15     1
3    24     2
4    23     3
5    12    10
6    10     6
7    28     5
8     9    14
9    23     2

In [78]:
df

var1  var2  var3
0     9     2    18
1     2    13    23
2    15     1    26
3    24     2    25
4    23     3     2
5    12    10     4
6    10     6     7
7    28     5    28
8     9    14    10
9    23     2    26

In [79]:
df.var1

0     9
1     2
2    15
3    24
4    23
5    12
6    10
7    28
8     9
9    23
Name: var1, dtype: int32

In [80]:
df.var1 > 15

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8    False
9     True
Name: var1, dtype: bool

In [81]:
df[df.var1 > 15]

var1  var2  var3
3    24     2    25
4    23     3     2
7    28     5    28
9    23     2    26

In [82]:
df[(df.var1 > 15) & (df.var3 < 15)] # aynı anda iki koşul

var1  var2  var3
4    23     3     2

# birleştirme (Join) işlemi

In [86]:
m = np.random.randint(1, 30, size=(5, 3))
df1 = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df1

var1  var2  var3
0    16     6    27
1    20    11     3
2    17    24     6
3     3    16     6
4     2     8    16

In [88]:
df2 = df1 + 99
df2

var1  var2  var3
0   115   105   126
1   119   110   102
2   116   123   105
3   102   115   105
4   101   107   115

In [91]:
pd.concat([df1, df2], axis = 1)

var1  var2  var3  var1  var2  var3
0    16     6    27   115   105   126
1    20    11     3   119   110   102
2    17    24     6   116   123   105
3     3    16     6   102   115   105
4     2     8    16   101   107   115

In [93]:
pd.concat([df1, df2], axis = 0, ignore_index=True)

var1  var2  var3
0    16     6    27
1    20    11     3
2    17    24     6
3     3    16     6
4     2     8    16
5   115   105   126
6   119   110   102
7   116   123   105
8   102   115   105
9   101   107   115

In [96]:
df2.columns = ["var1", "var2", "deg3"]
df2

var1  var2  deg3
0   115   105   126
1   119   110   102
2   116   123   105
3   102   115   105
4   101   107   115

In [97]:
df1.columns
df1

var1  var2  var3
0    16     6    27
1    20    11     3
2    17    24     6
3     3    16     6
4     2     8    16

In [98]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0    16     6  27.0    NaN
1    20    11   3.0    NaN
2    17    24   6.0    NaN
3     3    16   6.0    NaN
4     2     8  16.0    NaN
0   115   105   NaN  126.0
1   119   110   NaN  102.0
2   116   123   NaN  105.0
3   102   115   NaN  105.0
4   101   107   NaN  115.0

In [99]:
pd.concat([df1,df2], join = "inner")

var1  var2
0    16     6
1    20    11
2    17    24
3     3    16
4     2     8
0   115   105
1   119   110
2   116   123
3   102   115
4   101   107

# ileri Birleştirme join işlemleri

In [111]:
df1 = pd.DataFrame({"calisanlar": ["Ali", "Veli", "Ayse", "Fatma"],
              "grup": ["Muhasebe", "Muhendislik", "Muhendislik", "IK"]})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [121]:
df2 = pd.DataFrame({"calisanlar": ["Ayse", "Ali", "Veli", "Fatma"],
                    "işe_giris": [2010, 2009, 2014, 2019]})
df2


calisanlar  işe_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [122]:
pd.merge(df1, df2, on='calisanlar')

calisanlar         grup  işe_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [124]:
# çoktan teke birleştirme
df3 = pd.merge(df1, df2, on='calisanlar')
df3

calisanlar         grup  işe_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [125]:
df4 = pd.DataFrame({"grup": ["Muhasebe", "Muhendislik", "IK"],
                    "mudur": ["Caner", "Mustafa", "Berkcan"]})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [126]:
pd.merge(df3, df4, on="grup")

calisanlar         grup  işe_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

In [128]:
df5 = pd.DataFrame({"grup": ["Muhasebe", "Muhasebe","muhendislik", "muhendislik", "IK", "IK"],
                    "yetenekler": ["matematik", "excel", "kodlama", "linux", "excel", "yonetim"]})
df5


grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  muhendislik    kodlama
3  muhendislik      linux
4           IK      excel
5           IK    yonetim

In [130]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [131]:
pd.merge(df1, df5)

calisanlar      grup yetenekler
0        Ali  Muhasebe  matematik
1        Ali  Muhasebe      excel
2      Fatma        IK      excel
3      Fatma        IK    yonetim

# Toplulastirma ve Gruplama (Aggregation & Grouping)
    Basit toplulastirma fonksiyonlları:
        • count ()
        • first()
        • last()
        • mean()
        • median()
        • min()
        • max()
        • stdO
        • var()
        • sum()

In [134]:
import seaborn as sns

df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [135]:
df.shape

(1035, 6)

In [136]:
df.size

6210

In [139]:
df.mean()

C:\Users\Lenova\AppData\Local\Temp\ipykernel_18944\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [140]:
df["mass"].mean()

2.6381605847953216

In [141]:
df["mass"].count()

513

In [142]:
df["mass"].max()

25.0

In [143]:
df["mass"].min()

0.0036

In [144]:
df["mass"].sum()

1353.37638

In [145]:
df["mass"].std()

3.8186166509616046

In [146]:
df["mass"].var()

14.58183312700122

In [148]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [149]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama işlemleri

In [150]:
df = pd.DataFrame({"gruplar": ["A", "B", "C", "A", "B", "C"],
                    "veri": [10, 11, 52, 23, 43, 55]}, columns=["gruplar", "veri"])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [152]:
df.groupby("gruplar")


In [153]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [154]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [156]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [157]:
df.groupby("method")

In [158]:
df.groupby("method")["orbital_period"]

In [160]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [161]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [164]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# aggregate, filter, transform, apply